#! /usr/bin/env python
"""
    This is a generator of minimum jerk paths
"""
import numpy as np
from gsplines_msgs.msg import JointGSpline
import rospy
from gsplines import minimum_jerk_path
from gsplines_ros import gspline_to_joint_gspline_msg


def main():
    """
    Generic publisher loop
    """
    rospy.init_node('random_minimum_jerk_path_generator', anonymous=True)

    params = {}
    params['rate'] = 0.5
    params['codom_dim'] = 6
    params['joint_names'] = ["joint_{:d}".format(
        i) for i in range(params['codom_dim'])]
    params['number_of_waypoints'] = 3
    params['output_topic'] = 'random_minium_jerk_gspline'

    for key, value in params.items():
        params[key] = rospy.get_param('~'+key, value)

    pub_gsplines = rospy.Publisher(
        params['output_topic'], JointGSpline, queue_size=10)

    rate = rospy.Rate(params['rate'])

    while not rospy.is_shutdown():

        waypoints = np.random.rand(
            params['number_of_waypoints'], params['codom_dim'])

        trj = minimum_jerk_path(waypoints)

        pub_gsplines.publish(
            gspline_to_joint_gspline_msg(trj, params['joint_names']))

        rate.sleep()


if __name__ == "__main__":
    main()
