name: compilation
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push vim ros noetic with gsplines
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/vim-ros-noetic-gsplines-ros
          file: docker/noetic_ros.dockerfile
          push: true

      - name: build and push vim ros melodic with gsplines
        uses: docker/build-push-action@v2
        with:
          tags: rafa606/vim-ros-melodic-gsplines-ros
          file: docker/melodic_ros.dockerfile
          push: true
