name: compilation
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: /workdir
    container:
      image: ros:noetic-robot
      volumes:
        - ${{ github.workspace }}:/workdir
    steps:
      #      - name: checkout code
      #        uses: actions/checkout@master
      #        with:
      #          fetch-depth: 2
      #          submodules: recursive

      - name: Git Sumbodule Update ad build
        shell: bash
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            --no-install-recommends -o Dpkg::Options::="--force-confnew" \
            git ros-noetic-ifopt wget python3-catkin-tools \
            ros-noetic-joint-trajectory-controller \
            ros-noetic-joint-trajectory-action \
            ros-noetic-control-msgs
          source /opt/ros/noetic/setup.bash
          git clone --recursive \
            https://github.com/rafaelrojasmiliani/gsplines_cpp
          cd gsplines_cpp
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make -j2
          make install
          mkdir -p catkinws/src
          git clone https://github.com/rafaelrojasmiliani/gsplines_cpp_ros.git \
            catkinws/src/gsplines_cpp_ros
          cd catkinws
          source /opt/ros/noetic/setup.bash
          catkin build

#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: gsplines_cpp/build/gsplines-0.0.1-amd64.deb
#          asset_name: gsplines-0.0.1-amd64.deb
#          tag: package
#          overwrite: true
#          body: "Debian pack"
